apiVersion: v1
kind: ServiceAccount
metadata:
  name: lector-pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rol-lectura
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vinculacion-lectura
subjects:
  - kind: ServiceAccount
    name: lector-pods
roleRef:
  kind: Role
  name: rol-lectura
  apiGroup: rbac.authorization.k8s.io
