apiVersion: v1
kind: Pod
metadata:
  name: pod-con-configmap
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: mensaje-vol
          mountPath: "/config"
  volumes:
    - name: mensaje-vol
      configMap:
        name: mensaje-config
