apiVersion: v1
kind: Pod
metadata:
  name: pod-secreto
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["sh", "-c", "env | grep CLAVE_API && sleep 3600"]
      env:
        - name: CLAVE_API
          valueFrom:
            secretKeyRef:
              name: mi-secreto
              key: CLAVE_API
